### ISSUE TITLE
Node minter slowing RPC

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#135]
**Description**
Sometimes, around "Node minter" process, the RPC becomes very sluggish.

**Expected behaviour**
RPC should mostly respond, quickly.

**To reproduce**
Submit RPC requests around the time node minting happens

**System information**
CLI
Linux Ubuntu 20.04

**Comment by defunctec** [comment]
RPC remains sluggish due even with 100%+ server resource

**Comment by BlockMechanic** [comment]
Node minter solved
