### ISSUE TITLE
v0.0.0.62 getaddressdeltas parse error

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#137]
v0.0.0.62 getaddressdeltas parse error

**Expected behavior**
Should produce list of deltas for the specified address

**Actual behavior**

**To reproduce**
mark testnet3 $ tcrowncli getaddressdeltas '{"n2xTMYnpcvohenNq1vrsS5qYQXQYi69fMA"}'
error code: -1
error message:
JSON value is not an object as expected

No tested quoting/escaping combination works.

**System information**
v0.0.0.62

**Comment by BlockMechanic** [comment]
Insight, urgh. we will need a month or so for this alone
