### ISSUE TITLE
generatetoaddress coins don't show in wallet balance

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#14]
Coins created by `generatetoaddress` aren't showing up in `getbalance`, nor `getwalletinfo` but can be seen in `listtransactions`. Same happens for all address types, legacy, segwit and bech32.
 
**Expected behavior**
Coins should show up in `getwalletinfo` and `getbalance`

**Actual behavior**

**To reproduce**
```crown-cli getnewaddress
crown-cli generatetoaddress 1 <new_address> 
crown-cli getwalletinfo
```
 

**System information**

Crown Core version v21.99.0-gaf591f2068d0363c92d9756ca39c43db85e5804c (release build)
tag 0.0.0.4

Ubuntu 20.04

**Comment by BlockMechanic** [comment]
Confirmed, appears the add to wallet function is not working properly.

**Comment by walkjivefly** [comment]
Situation is improved with 0.0.0.5 but we still need to set the default asset type to CRW (or tCRW for testnet).

```
crown@crown-testnet-05:~/.crown/testnet3$ crown-cli getwalletinfo
{
  "walletname": "xmn05",
  "walletversion": 169900,
  "format": "bdb",
  "balance": {
    "": 312000.00000000
  },
  "unconfirmed_balance": {
  },
  "immature_balance": {
    "": 10000.00000000
  },
  "txcount": 3220,
  "keypoololdest": 1641841704,
  "keypoolsize": 999,
  "hdseedid": "d23b7e0e45ce112d8ada6a80d6458f2d23ad12b8",
  "keypoolsize_hd_internal": 1000,
  "unlocked_until": 0,
  "paytxfee": 0.00000000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false
}
crown@crown-testnet-05:~/.crown/testnet3$ crown-cli getbalance
{
  "": 312000.00000000
}
```
