### ISSUE TITLE
v0.0.0.62 QT wallet displays incomplete balances

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#140]
QT wallet shows incomplete balances on overview panel

**Expected behavior**
Balance display should include total balance, not only spendable 

**Actual behavior**
![image](https://user-images.githubusercontent.com/17745270/197349674-8ed7b2e4-8c79-4d46-9466-746c9d8cdc29.png)

vs (slightly different time)
```
mark testnet3 $ tcrowncli getbalances
{
  "mine": {
    "trusted": {
      "Crown": 2001.05225400
    },
    "untrusted_pending": {
    },
    "immature": {
      "Crown": 117.00000000
    },
    "stake": {
    },
    "locked": {
      "Crown": 21000.00000000
    },
    "used": {
      "Crown": 28322.40149670
    }
  },
  "watchonly": {
    "trusted": {
      "Crown": 2001.05225400
    },
    "untrusted_pending": {
    },
    "immature": {
    }
  }
}
```

**System information**
v0.0.0.62 on linux

The value returned by `getbalance` (total spendable with no action from the user) has changed in this release from the behaviour in v0.14 (total available in the wallet).

People with MN/SNs are likely to be surprised and upset to see their balance drop due to the amount locked in nodes. 

We should restore the previous getbalace behaviour and hence QT balance display or add additional fields in the QT wallet to show locked and total balances.

**Comment by BlockMechanic** [comment]
This issue requires some redesigning of teh interface, see the video i linked you in discord DMs

**Comment by BlockMechanic** [comment]
The title implies something is missing. Let's take a step back from what we see now and look a bit broader. The GUI space is at a premium and thus must be used wisely. Take my balances as an example : 
![Screenshot from 2022-10-27 02-32-44](https://user-images.githubusercontent.com/24528627/198163804-ae45856f-f99b-4191-b063-85f72bc887ea.png)

Do you see how very quickly the space is taken up by having balances in several assets? And this is without even the watch only balances being visible. Now, what if i had 200 assets ? A haphazard solution would end up being crowded and likely very messy. Fixing the actual issue as you say is indeed the accepted approach, but in this case it's not just code, it's the whole layout we need to re-think and then start coding it. I did not close this to dismiss the issue, but to set it aside as it's scope and requirements may not be the best use of our limited time and resources for the upcoming update.
