### ISSUE TITLE
v0.0.0.62 reinstate CRW prefix 

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#145]
v0.14 uses unique CRW and tCRW prefix for legacy addresses. A unique prefix is a pre-req for Trezor integration. Having achieved the integration it would be nice to retain it, so ideally the new codebase should also adopt the same prefixes.

Conceivably exchanges might also take a dim (relisting) view of changing the prefix since they'll claim it's extra work for their receiving addresses.

**Comment by BlockMechanic** [comment]
This is now resolved 
![Screenshot from 2022-10-26 04-04-52](https://user-images.githubusercontent.com/24528627/197917599-83a77294-2c92-4f62-9bf3-e72d3b520f9d.png)
