### ISSUE TITLE
Asset TX fee should be Crown only

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#153]
Self descriptive

**Comment by BlockMechanic** [comment]
The only part is under debate, but fees do now include a CRW component.

**Comment by defunctec** [comment]
After successfully sending an asset to myself there is still a deduction of asset for fee
![image](https://user-images.githubusercontent.com/9864793/205974113-fc4da499-39a6-44cb-ba78-b4320cac4c5e.png)

**Comment by defunctec** [comment]
Trying to send asset via QT "Send" tab but...
![image](https://user-images.githubusercontent.com/9864793/207671182-5f799c2e-9fbe-47e3-905f-e46b525764ef.png)

Asset sending works via console

**Comment by defunctec** [comment]
Ahh, you need to select a CRW output for use as fee.
Otherwise works
