### ISSUE TITLE
New "MN/SN" button causes crash

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#158]
**Description**
Trying to created a Masternode or Systemnode via the "New" button does not work.

**Expected behaviour**
New window is opened when button is pressed.

**To reproduce**
Click the "New Masternode" button within the Masternode tab

**System information**
QT
Linux Ubuntu 22.04

**Comment by defunctec** [comment]
"Nice to have" binned

**Comment by BlockMechanic** [comment]
fixed in 0.0.0.66
