### ISSUE TITLE
No way to list asset types

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#18]
With tag 0.0.0.5, according to `crown-cli help` there appears to be no way to list asset types.

**Expected behavior**
It should be possible to list asset types otherwise how will you know what assets are valid to send?

**System information**
Tag 0.0.0.5, Ubuntu 20.04

**Comment by BlockMechanic** [comment]
Ah, this is a feature request. Will bang something up, though feature requests are a bit lower in priority to bugs.

**Comment by walkjivefly** [comment]
We could argue about the semantics of missing essential functionality but let's just get something implemented. I'm surprised if that functionality doesn't already exist in whichever code tree from which we acquired `sendtoaddress` which requires an asset type to tell it what to send. Also surprised it doesn't default to the base asset class....

**Comment by BlockMechanic** [comment]
I think between the help on createaseet and the details you get from getassets , this is resolved. reopen if not.
