### ISSUE TITLE
v0.0.0.68 QT incorrout sending/receiving addresses/labels display

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#185]
QT wallet doesn't show all known labels, and mangles the names of those it does display, eg:
![Screenshot_2022-11-06_14-18-50](https://user-images.githubusercontent.com/17745270/200173039-f2f3facb-0506-4cca-9183-5f1b0cac430d.png)
Compare and contrast the (receiving) labels shown in QT with the `listlabels` result in CLI. The xng* labels are watch addresses in other wallets. All of the "local" labels addresses have been used for receiving funds.

The "missing" labels show up in the QT sending labels tab but are missing important little details, like the actual address.
![Screenshot_2022-11-06_14-25-46](https://user-images.githubusercontent.com/17745270/200173398-01981212-0601-4887-9e57-8e2f2770b132.png)

**Comment by BlockMechanic** [comment]
That is likely a consequence of the change in prefix. Addresses are dealt with differently

**Comment by walkjivefly** [comment]
This seems to be resolved in 0.0.0.75; at least all labels display an address, and all those I checked are correct.
