### ISSUE TITLE
Mac QT crashes when creating a MN - I name my MN, put the VPS ip then hit the button, takes me to the message which says I am sending 10k, I hit ok then crash

### ISSUE THREAD

**Issue by crowncoinknight** [Crowndev/crown#187]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by walkjivefly** [comment]
Same thing happens creating a node in v0.0.0.72 on linux, eg:
![Screenshot_2022-11-16_14-26-15](https://user-images.githubusercontent.com/17745270/202194318-1f9e64b8-8647-4531-a413-ef91fb784223.png)
then
![Screenshot_2022-11-16_14-27-05](https://user-images.githubusercontent.com/17745270/202194378-c65cb53a-8749-4bfe-88e6-83c157e1b92b.png)
then 
![Screenshot_2022-11-16_14-27-32](https://user-images.githubusercontent.com/17745270/202194437-41769ed4-b20e-4ae5-963e-5b95cccc9faa.png)
then
![Screenshot_2022-11-16_14-28-00](https://user-images.githubusercontent.com/17745270/202194481-b731e58f-b557-4a62-a6d3-35ad6bc88120.png)

and it crashes with SIGSEGV.

**Comment by walkjivefly** [comment]
And why did it ask for the node alias and IP address twice?

**Comment by walkjivefly** [comment]
Exactly the same thing still happening in 0.0.0.74 on linux

**Comment by BernardCornfeld** [comment]
At least under mac it does work now.
