### ISSUE TITLE
v0.0.0.72 incorrout from `gettransaction`

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#201]
This is a follow-on to https://github.com/Crowndev/crown/issues/172.
The output from `gettransaction` is incorrect. I made a test transaction 77c120f80d3d91515bbf7e0c78b98740d9058dda9d393bf38dc36dfe6da720a9 using coin control in the QT wallet to send 9.87654321 tCRW from address tCRWDFPGUwUZSxEDGfqteFRxMkkZp6pkrSQxk to address tCRWGPWT6843C6SQpEMEt1rMDjqm7UKEgkaHf with change address tCRWFnWjpHXLBP5VAxurtXR8sYMmRchQSr5NG and a fee of 0.00000427 tCRW:
![Screenshot_2022-11-16_12-15-54](https://user-images.githubusercontent.com/17745270/202171362-686b0f09-1942-4544-bbcc-94fdb20f47ef.png)

This is decoded/displayed by `gettransaction` as
```
mark@xub22:~/.crown/testnet3$ crown-cli gettransaction 77c120f80d3d91515bbf7e0c78b98740d9058dda9d393bf38dc36dfe6da720a9
{
  "amount": {
    "": 602.27166774,
    "Crown": -602.27166774
  },
  "fee": {
    "Crown": -0.00000427
  },
  "confirmations": 21,
  "blockhash": "2aec76621c76982288f7046b921020c4a05bd4e8242342118b9cebd5767a82ff",
  "blockheight": 39723,
  "blockindex": 2,
  "blocktime": 1668597547,
  "txid": "77c120f80d3d91515bbf7e0c78b98740d9058dda9d393bf38dc36dfe6da720a9",
  "walletconflicts": [
  ],
  "time": 1668597448,
  "timereceived": 1668597448,
  "bip125-replaceable": "no",
  "details": [
    {
      "address": "tCRWGPWT6843C6SQpEMEt1rMDjqm7UKEgkaHf",
      "category": "send",
      "amount": -9.87654321,
      "asset": "0000000000000000000000000000000000000000000000000000000000000000",
      "label": "receivetest",
      "vout": 1,
      "fee": {
        "Crown": -0.00000427
      },
      "abandoned": false
    },
    {
      "address": "tCRWGPWT6843C6SQpEMEt1rMDjqm7UKEgkaHf",
      "category": "receive",
      "amount": 9.87654321,
      "asset": "0000000000000000000000000000000000000000000000000000000000000000",
      "label": "receivetest",
      "vout": 1
    }
  ],
  "hex": "0400000000b8c6746301c33b86ac9ce54deb6daeaf72efd4916edc91eb533d09be1435ab2c7be06651f5000000006a47304402206485129f9ac7e9578c2fd4616f7c064f22965296ac1b2a0cbb409e8f84a0ffad022066e98bc1b08d9cffaaf7222705686112f80f4f94f7969c2e3a48cf07dfe6a647012103992e6ef35069a5559b7091a17cb4b393d5b95296cbd514d9c72f50f901a74474fdffffff028539f3ca0d0000001976a9141ea9c00da01bee8fc2a20e2595e923057469d50c88ac080901000000130000000100000000000000303030303043726f776e003043525700000000000000000000000000000000000000000000000000000000000000000001e406970c686af865acef75d340c2487ad4e865f42b0df4e2f46c4d30dd9218b168de3a000000001976a91425481170f5d7c5d904b09cf22f60bd62744a2a4588acd08e01000000130000000100000000000000303030303043726f776e003043525700000000000000000000000000000000000000000000000000000000000000000001e406970c686af865acef75d340c2487ad4e865f42b0df4e2f46c4d30dd92182a9b000000"
}
```
which is *MANY* kinds of wrong. 
First off, there was no debit from tCRWGPWT6843C6SQpEMEt1rMDjqm7UKEgkaHf; that was the target receive address.
Secondly, the change vout is not shown.

**Comment by BlockMechanic** [comment]
Have you tried with the optional boolean for verbose output ?

**Comment by walkjivefly** [comment]
My bad, again, regarding the change output. Sorry. I'm used to seeing the change even in non-verbose output in some other coins and it's apparently a long time since I've looked at the `gettransaction` output in v0.14 because that doesn't even show any of the vouts for an intra-wallet tx. 

Showing both a debit from and a credit to the _destination_ address on an intra-wallet txn seems unnecessarily confusing and could perhaps be improved in the future. In the mean time, the verbose view does indeed give a better picture of what the txn involved.
