### ISSUE TITLE
Starting SN Via QT does start MN

### ISSUE THREAD

**Issue by BernardCornfeld** [Crowndev/crown#210]
When marking a SN in the SN list and pressing "start alias" one would suspect that the QT starts the SN, but the MN which is selected in the left list does get startet. 
![image](https://user-images.githubusercontent.com/118539818/202800508-758bf2d8-3bf2-4f8b-858f-9ab2b349cdfb.png)
![image](https://user-images.githubusercontent.com/118539818/202800564-2fe1bbf1-b1c5-482d-aee6-8c07084658a0.png)

Tested under macOS 12.6 with the latest release.

**Comment by BernardCornfeld** [comment]
Persitsing...

**Comment by defunctec** [comment]
This is still an issue on 0.79. The gui always wants to start a MN when trying to start a SN (even when not highlighted)
