### ISSUE TITLE
GUI Contract creation doesn't show fail reason

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#212]
When making a contract within the GUI and the address is unfunded for example, after clicking create there is no error message notifying the user as to why it failed.

The client should pop a notification up explaining the reason for failure.

Also when successful in creating contract, only the notification of coins being spent is popped up. 

There should be a notification once again saying that creation was a success

**Comment by walkjivefly** [comment]
In GUI:

1. created receiving (contract) address
2. funded the address with 11 tCRW
3. created a contract (MRBL), toast showed 10 CRW sent to blackhole
4. contract didn't show up immediately
5. sent another 51 tCRW to the contract address ready to create assets
6. contract still didn't show up
7. waited a few more blocks
8. contract still didn't show up
9. repeated the create contract (MRBL) process
10. explorer shows change and burn in 13cc570fab2006ea0ef0bcaa996430c29e26140539729f34ca48c2ced38e0a2f
11. MRBL contract now shows up in contracts window but a previously created contract (WOTS) is not showing (but still present in console window in `getcontracts`
12. sent 1 tCRW to the missing contract (WOTS) address
13. WOTS still didn't show up in contracts window
14. sent 10 tCRW to WOTS address
15. WOTS still doesn't show up in contract window 
.

**Comment by defunctec** [comment]
I see WOT's contract
![image](https://user-images.githubusercontent.com/9864793/202910773-64f7fb10-cf7f-4d15-b484-772629d5d44a.png)

**Comment by defunctec** [comment]
Fixed
