### ISSUE TITLE
No field to name asset

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#213]
There is no place to name an asset when creating with the GUI.

![image](https://user-images.githubusercontent.com/9864793/202845360-38c0e1f9-bd63-4028-a5fa-885685922108.png)

**Comment by defunctec** [comment]
Also stackable is missing

**Comment by BlockMechanic** [comment]
Stake option being removed. To prevent users from trying to create assets with names different from the contract, you can only select a contract form the drop down and it automates the rest, no direct naming for now
