### ISSUE TITLE
Incorrect shortname used when confirming send an asset

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#215]
Some visual issues relating to displaying the correct asset shortname when sending assets.

Here I'm attempting to send an asset but in the confirm box it shows that " 10.00000 CRW" is being sent and not "def"
![image](https://user-images.githubusercontent.com/9864793/202845998-ba938682-57e7-4c7a-9fff-387690c54db9.png)

More here
![image](https://user-images.githubusercontent.com/9864793/202846808-99319a09-6bd6-4f2f-b4c3-726dd9687387.png)

**Comment by BlockMechanic** [comment]
The "CRW "  is referring to unit size, we would have to discuss what new names to call units.

**Comment by defunctec** [comment]
For me the client should obtain the asset "shortname" and switch between which asset is selected replacing "CRW" "mCRW" "uCRW"

**Comment by BlockMechanic** [comment]
New version out

**Comment by defunctec** [comment]
Trying to send an asset, QT still shows "CRW"
![image](https://user-images.githubusercontent.com/9864793/205111993-c2697e53-c82c-4c0e-becf-7b9cf5442083.png)

**Comment by defunctec** [comment]
So much better with 0.82
