### ISSUE TITLE
Remove assets from "money supply"

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#216]
Using getblockchaininfo shows money supply but it's also showing all other assets. In the future this will cause problems since potentially thousands of assets could make the getblockchaininfo command unusable.

![image](https://user-images.githubusercontent.com/9864793/202847541-b567206f-5ecc-4fbb-af8e-69c8af8e7112.png)

**Comment by BlockMechanic** [comment]
needs input from the others, this could at times be exactly the info someone wants to retrieve

**Comment by BlockMechanic** [comment]
maybe a verbose option?

**Comment by defunctec** [comment]
I suppose it's a nice problem to have, nothing which can't be addressed going forward
