### ISSUE TITLE
v0.0.0.75 GUI create asset toast incorrout

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#219]
v0.0.0.75 linux GUI
Created an asset, 1000000 WOTS(its) for 100 CRW. 
The "incoming transaction" toast popped up saying 1000000 **CRW** received.

**Comment by defunctec** [comment]
Related to #215

**Comment by walkjivefly** [comment]
in 0.0.0.78 the toast shows the CRW spent, doesn't mention the created asset. At least there's no mix up now.
