### ISSUE TITLE
v0.0.0.75 balances are broken

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#223]
The upper bound for asset creation isn't documented. Experimentation shows it is 999999999 (see MRBL) but the asset doesn't show in the send window asset selection pulldown. Also breaks `getbalances`

```
mark@xub22:~/.crown/testnet3$ crown-cli getbalances
error code: -1
error message:
GetAvailableCredit : value out of range
```

**Comment by defunctec** [comment]
I can't see MRBL on my side of things

**Comment by BlockMechanic** [comment]
Contract seen, no asset. A limit is being discussed , see chat

**Comment by walkjivefly** [comment]
hmmm, maybe the asset(s) didn't get created because of the previous conflicted. 

Or maybe they did. I just tried again and they seem to have been created, but don't show up in overview, nor coin control (but nor do WOTSits), and `getbalances` and `getwalletinfo` are broken.
![Screenshot_2022-11-20_20-03-59](https://user-images.githubusercontent.com/17745270/202920953-ff5e8c4f-5810-4bdb-927b-9d8c1c22ce55.png)
```
mark@xub22:~/.crown/testnet3$ crown-cli getbalances
error code: -1
error message:
GetAvailableCredit : value out of range
mark@xub22:~/.crown/testnet3$ crown-cli getwalletinfo
error code: -1
error message:
GetAvailableCredit : value out of range
```

**Comment by walkjivefly** [comment]
debug.log is now spammed with gazillions of
```
2022-11-21T09:14:07Z GUI: std::runtime_error in thread :  0x7f64c72ec800
2022-11-21T09:14:07Z GUI: GetAvailableCredit : value out of range
2022-11-21T09:14:07Z GUI: std::runtime_error in thread :  0x7f64c72ec800
2022-11-21T09:14:07Z GUI: GetAvailableCredit : value out of range
2022-11-21T09:14:07Z GUI: std::runtime_error in thread :  0x7f64c72ec800
2022-11-21T09:14:07Z GUI: GetAvailableCredit : value out of range
2022-11-21T09:14:08Z GUI: std::runtime_error in thread :  0x7f64c72ec800
2022-11-21T09:14:08Z GUI: GetAvailableCredit : value out of range
2022-11-21T09:14:08Z GUI: std::runtime_error in thread :  0x7f64c72ec800
2022-11-21T09:14:08Z GUI: GetAvailableCredit : value out of range
```
messages.

**Comment by walkjivefly** [comment]
This also causes the balances in the GUI to not update; it shows the same balances now as a day ago.

**Comment by walkjivefly** [comment]
Oh what fun, closed the QT wallet and restarted, it doesn't get past the splash screen and can't be shutdown by clicking the close icon.

**Comment by walkjivefly** [comment]
in 0.0.0.78 the enforced asset cap ratio prevents the situation which probably led to this balance problem.
Closing for now.

**Comment by walkjivefly** [comment]
Re-opening with new occurrence of previously seen problem: not all balances are reported in the GUI dashboard or by getbalances.
I created 1000 WOTSits, they showed up OK in balances.
I created 10000 Marbles, they showed up in balance but the WOTSits disappeared.
![Screenshot_2022-11-28_18-29-25](https://user-images.githubusercontent.com/17745270/204342655-4e92dbb1-6fd9-42b8-8aa3-5e0d3bda3887.png)
The WOTSits are also no longer visible in Assets page nor in coin control.

**Comment by BlockMechanic** [comment]
Please check/verify that your asset was actually created. I can retrieve data for Marbles contract and asset, but there is no asset Wotsits on the chain, just a contract. Can you try a console creation as well and tell us the results ?
