### ISSUE TITLE
v0.0.0.75 not all contracts show in the Asset Manager contract panel

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#225]
Known contracts are
```
mark@xub22:~/.crown/testnet3$ crown-cli getcontracts|grep '"symbol"'
    "symbol": "MRBL",
    "symbol": "LTC",
    "symbol": "tNFT",
    "symbol": "def",
    "symbol": "BTC",
    "symbol": "WOTS",
    "symbol": "TST",
```
but only 5 of these are visible in Asset Manager contract panel:
![Screenshot_2022-11-21_09-52-12](https://user-images.githubusercontent.com/17745270/203006663-ea64cca6-33c8-4f14-8cbb-aef8dddb30da.png)

**Comment by walkjivefly** [comment]
hasn't immediately reproduced in 0.0.0.78

**Comment by BlockMechanic** [comment]
I've had to make adjustments on display/update rules. Typically it should have just shown new contracts as they are detected in new blocks. That was causing a delay in sync as the GUI would then query the DB even during initial sync. So to prevent this, it no longer does so during sync, only when blocks, MN/SN and budget data is synced does it start updating on a per block basis.
