### ISSUE TITLE
linux 0.0.0.78 GUI contract creation requires>11 CRW

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#234]
Contract creation now costs more than 10 CRW.
Probable (unintended?) consequence of enforcing 1:100 asset creation ratio?

**Comment by walkjivefly** [comment]
11 CRW in the funding address didn't work.
Added another 100+ CRW, contract creation worked.

**Comment by BlockMechanic** [comment]
Price has gone up as stated in chat. 100 CRW for a contract. Inflation and all.

**Comment by BlockMechanic** [comment]
> Contract creation now costs more than 10 CRW. Probable (unintended?) consequence of enforcing 1:100 asset creation ratio?

The ratio is a max value and only applies at actual asset creation. You can use any lower ratio if you decide.
