### ISSUE TITLE
QT wallet showing non recognised character on wallet value

### ISSUE THREAD

**Issue by DutchShadow** [Crowndev/crown#87]
Dot/comma seperating whole coins in the overview/dashboard bugs out.

**Expected behavior**

The value being given with 50,000.XX or 50.000,XX 

**Actual behavior**

![image](https://user-images.githubusercontent.com/1141616/180712954-a90bb3da-6fb1-4a04-bf3d-3a9dd081cc31.png)

**To reproduce**

Set the wallet to Dutch/Netherlands locale

**System information**

v21.99.2-gaf591f2068d0363c92d9756ca39c43db85e5804c

Windows, auto set to Dutch language

**Comment by BlockMechanic** [comment]
Locale issues are notoriously difficult to resolve but i''ll do what i can
