### ISSUE TITLE
Asset get's unselected in QT and leads to insufficient funds error

### ISSUE THREAD

**Issue by DutchShadow** [Crowndev/crown#88]
after sending 10k for MN creation I had to restart wallet to get the standard settings  
![image](https://user-images.githubusercontent.com/1141616/180757100-56eba0b4-0d5d-436b-b4dc-559025212b5d.png)

**Expected behavior**

After a transaction is sent the next transaction is ready as Crown asset.

**Actual behavior**

![image](https://user-images.githubusercontent.com/1141616/180757360-c3cdad6f-d9f6-4703-96cc-46ca6a8e9524.png)

**To reproduce**

Send a transaction or add a recipient

**System information**

**Comment by BlockMechanic** [comment]
Fixed
