### ISSUE TITLE
Collateral not locking (CLI & QT)

### ISSUE THREAD

**Issue by pjcltd** [Crowndev/crown#91]
Entering txid into masternode.conf and restarting the client does not lock the collateral and can be used again.

Expected behaviour
After the addition of txid to masternode.conf and systemnode.conf and a client restart, collateral should be locked.

To reproduce
Create the first MN, close the wallet and create MN2. MN1 collateral is being used to form MN2

System information
CLI & QT
Linux Ubuntu 22.04

**Comment by BlockMechanic** [comment]
This should be resolved now

**Comment by walkjivefly** [comment]
Collateral is locked, shows as such in `listlockunspent` but  not in `getmasternodeoutputs` or `getsystemnodeoutputs`
